# Generated by Django 4.1.3 on 2024-07-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_id', models.CharField(max_length=10, verbose_name='部门ID')),
                ('name', models.CharField(max_length=10, verbose_name='部门名称')),
                ('depart_status', models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='部门状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'sys_department',
            },
        ),
        migrations.CreateModel(
            name='Personal_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '病假'), (2, '事假')], verbose_name='请假类型')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('user_id', models.CharField(max_length=7, verbose_name='员工ID')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('reason', models.CharField(max_length=100, verbose_name='请假原因')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('check_status', models.IntegerField(choices=[(1, '待审核'), (2, '审核通过'), (3, '审核不通过')], default=1, verbose_name='审核状态')),
            ],
            options={
                'db_table': 'sys_Personal_leave',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('user_id', models.CharField(max_length=7, verbose_name='员工ID')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('user_status', models.IntegerField(choices=[(1, '在职'), (2, '离职')], default=1, verbose_name='用户状态')),
                ('position', models.CharField(max_length=10, verbose_name='职位')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户账号')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_manage.department', verbose_name='部门')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
