# Generated by Django 4.1.3 on 2024-07-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='sys_department_',
        ),
        migrations.AlterModelTable(
            name='personal_leave',
            table='sys_Personal_leave_',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sys_user_',
        ),
    ]
